# Datasource
datasource:
  driver-class-name: org.postgresql.Driver
  url: jdbc:postgresql://localhost:5432/limardb
  username: lima
  password: 1111
# JPA
jpa:
  hibernate:
    ddl-auto: update # When you launch the application for the first time - switch "none" at "create"
  show-sql: true
  database: postgresql
  database-platform: org.hibernate.dialect.PostgreSQLDialect
  open-in-view: false
  generate-ddl: true

spring:
  main:
    allow-bean-definition-overriding: true
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        hbm2ddl:
          auto: update
  # Redis
  data:
    redis:
      host: localhost
      port: 6379
server:
  port: 8090